spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
env:
  s3.endpointUrl: http://s3.amazonaws.com

logging.level:
  root: INFO
  org.superbiz.moviefun: DEBUG

